import { parseMindMap } from "../../service/ParseMindMap";
import { MindMapNode } from "./MindMapNode";

export const PdfLayout = ({ contentData, selectedChapter }: any) => {
    if (!contentData) return null;
    return (


        <div style={{ fontFamily: "Arial", padding: "24px", background: "white" }}>

            {/* 📘 COVER PAGE */}
            <div style={{
                textAlign: "center",
                marginTop: "200px"
            }}>
                <h1 style={{ fontSize: "36px" }}>Study Notes</h1>
                <h2 style={{ marginTop: "20px" }}>
                    Chapter {selectedChapter}
                </h2>

                <p style={{ marginTop: "40px", color: "gray" }}>
                    Generated by Tank Student Platforms
                </p>
            </div>

            <div style={{ pageBreakAfter: "always" }} />

            {/* 📝 NOTES */}
            <h2 style={{ borderBottom: "2px solid #ccc" }}>📘 Notes</h2>

            {contentData.notes?.map((item: any, i: number) => (
                <div key={i} style={{
                    background: "#f9fafb",
                    padding: "12px",
                    borderRadius: "8px"
                }}>
                    <strong style={{
                        fontSize: "15px",
                        display: "block",
                        marginBottom: "4px"
                    }}>{i + 1}. {item.note}</strong>
                    <p style={{
                        fontSize: "14px",
                        lineHeight: "1.6",
                        color: "#333"
                    }}>{item.explanation}</p>
                </div>
            ))}

            <div style={{ pageBreakBefore: "always" }} />

            {/* 🧠 MIND MAP */}
            <h2>🧠 Mind Map</h2>
            <MindMapNode node={parseMindMap(contentData.mindMap)} />

            <div style={{ pageBreakBefore: "always" }} />

            {/* ❓ QUESTIONS */}
            <h2>❓ Questions</h2>

            {contentData.questions?.map((q: any, i: number) => (
                <div key={i} style={{
                    border: "1px solid #e2e8f0",
                    borderRadius: "8px",
                    padding: "12px",
                    marginBottom: "16px",
                    background: "#fafafa"
                }}>
                    <p><strong>Q{i + 1}.</strong> {q.question}</p>

                    {q.options.map((opt: string, idx: number) => (
                        <p style={{
                            marginLeft: "12px",
                            fontSize: "14px"
                        }} key={idx}>• {opt}</p>
                    ))}

                    <p style={{
                        color: "#2f855a",
                        fontWeight: "bold",
                        marginTop: "6px"
                    }}>
                        ✅ Answer: {q.answer}
                    </p>
                </div>
            ))}

            <div style={{
                position: "fixed",
                bottom: "10px",
                width: "100%",
                textAlign: "center",
                fontSize: "12px",
                color: "#888"
            }}>
                Chapter {selectedChapter} • Tank Student Platform
            </div>
        </div>
    );
};